version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            python -m pip install -r requirements-dev.txt
      - run:
          name: linter
          command: |
            . venv/bin/activate
            flake8 --statistics
      - run:
          name: unit tests
          command: |
            . venv/bin/activate
            python -m pytest tests -v --cov
